### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by moh1122** [Chris-Perkins/Lifting-Buddy#4]
failed to emit precompiled header '/Users/m/Library/Developer/Xcode/DerivedData/Lifting_Buddy-gusdukxpydhkhjcnidbttymfdxod/Build/Intermediates.noindex/PrecompiledHeaders/Lifting-Buddy-Bridging-Header-swift_14AEMUSNKZQ0Y-clang_1G4FM8PL0TO48.pch' for bridging header '/Users/m/Desktop/Newapps/Lifting-Buddy-master/Lifting-Buddy-master/Lifting Buddy/Lifting-Buddy-Bridging-Header.h'

**Comment by Chris-Perkins** [comment]
Hey there moh! In order to debug this I just need to ask a few clarifying questions.
1. What version of XCode are you using when you receive this error?
1. Are there any other errors you see, or is it just the error given?
1. Are you opening the ```.xcworkspace``` or the  ```.xcodeproj``` file?
1. What do you see under the ```./Externals/``` file directory for the project?
1. What do you see under the ```./Pods/``` file directory for the project?

**Comment by Chris-Perkins** [comment]
Hey moh, just following up. Were you able to resolve the issue on running the project?

**Comment by Chris-Perkins** [comment]
Closing this issue due to a lack of response. If this issue pops up for anyone else, please make sure you clone the repository recursively.
You may clone recursively using:
```
git clone --recursive https://github.com/Chris-Perkins/Lifting-Buddy.git
```
Simply cloning does not work since I have a submodule for the draggable tableview.
